events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name localhost;

        # Prometheus
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Grafana
        location /grafana/ {
            proxy_pass http://grafana:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Root
        location / {
            return 200 'Future frontend service';
            add_header Content-Type text/plain;
        }
    }
}