# Nom de l'application
spring.application.name=frontend-service

# Port sur lequel le conteneur va écouter (doit correspondre à ton nginx.conf)
server.port=8080

# Configuration Thymeleaf (pour recharger les templates sans redémarrer en dev)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuration Kafka (pour éviter que Spring ne crash si la connexion met du temps)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# Optionnel : Ajuste le timeout pour éviter les blocages infinis au démarrage
spring.kafka.admin.properties.max.block.ms=5000